### ISSUE TITLE
Unable to add LICENSE files in the nbm archive

### ISSUE THREAD

**Issue by tmess567** [mojohaus/nbm-maven-plugin#23]
I am building a netbeans plugin as an nbm archive file. But unlike the jar file, this archive does not contain the LICENSE files inside the META-INF subdirectory. This is causing trouble and is unable to work with the ianal plugin (See [IANAL](https://mvnrepository.com/artifact/org.codehaus.mojo/ianal-maven-plugin)) available for maven.
I've tried using nbmResource but it puts the resources in the netbeans subdirectory of the archive which is not accepted by the ianal plugin. Is there some workaround to adding these resources to the META-INF subdirectory of the nbm archive?

**Comment by mkleint** [comment]
well, the nbm file is just a zip file effectively, if you really need it, try taking the nbm and adding the license file ex post. But the nbm files just have a different location for the licensing (inside it's own metadata files) so IANAL plugin might not be the best option here, especially since it's effectively abandoned I believe.

**Comment by tmess567** [comment]
Could you point me to an appropriate plugin that I should use in this situation. Disabling or alternating ianal with something else is not possible.

**Comment by mkleint** [comment]
not from top of my head. maybe the antrun plugin that allows scripting
